"""followers

Revision ID: 5cbeb7e5f711
Revises: 83484f1e03b3
Create Date: 2023-01-31 10:57:00.813122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cbeb7e5f711'
down_revision = '83484f1e03b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user_model.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user_model.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
