"""PostModel table

Revision ID: 72d9d3acff6f
Revises: 78588c0bb815
Create Date: 2023-01-22 12:08:29.164185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d9d3acff6f'
down_revision = '78588c0bb815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=768), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_model', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_model_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_model', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_model_timestamp'))

    op.drop_table('post_model')
    # ### end Alembic commands ###
