"""new fields: about_me and last_seen in UserModel

Revision ID: 83484f1e03b3
Revises: 72d9d3acff6f
Create Date: 2023-01-23 00:38:45.941923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83484f1e03b3'
down_revision = '72d9d3acff6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
